도메인 구조 설계
ggplay149/OrderManagementSystem pull request #3
Opened 2024-09-24 13:50 UTC by ggplay149

멀티모듈 구조, 도메인 엔티티 설계 진행하였습니다.

2024-09-25 10:16 UTC, DongHyukki requested changes
수고하셨습니다.

멀티모듈 관련해서는 이따 코멘트 드릴게요

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/Cart.java
> +@Table(name = "cart")
보통은 테이블 이름은 복수로해요 `carts`

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/CartItem.java
> +@Table(name = "cartItem")
테이블 이름은 camelCase 보단 snake_case 를 사용합니다 `cart_items`

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/Cart.java
> +    @Column(name = "id", columnDefinition = "varbinary(16)")
UUID 를 사용하더라도 타입 자체를 UUID 로 두기보다는 String 으로 두는것이 좋습니다~!

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    @Column(name="status", nullable = false)
이렇게 두면 jpa 특정상 다른방식으로 저장되는데요. 요건 추후에 save 해보시고 어떻게 되는지 보고 수정해보시면 좋을거 같습니다.

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    private LocalDateTime createdAt;
updatedAt 은 필요없나요? + 보통은 BaseEntity 를 두고 createdAt, updatedAt, createdBy, updatedBy 설정후 
상속 받아 엔티티 만듭니다.

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/OrderItem.java
> +    @Column(name = "orderName", nullable = false) //주문당시 상품명
productName 이 더 어울리지 않나요?

2024-09-25 10:16 UTC, DongHyukki commented on order/src/main/java/domain/OrderItem.java
> +    @Column(name = "orderPrice", nullable = false) //주문당시 상품가격
여기도 productPrice 가 더 어울리지 않을지

2024-09-25 10:16 UTC, DongHyukki commented on payment/src/main/java/domain/Payment.java
> +    private BigDecimal amount;
금액이나 가격은 별도의 `1급 객체`를 두는게 좋습니다.

2024-09-25 10:16 UTC, DongHyukki commented on product/src/main/java/domain/Inventory.java
> +    private BigDecimal stock;
재고를 BigDecimal 로 두신 이유가 있나요?

2024-09-25 12:25 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    @ManyToOne(optional = false)
엔티티들 전부 (다) 쪽에 단방향만 걸려있는거 같은데 이유가 있나요?

2024-09-27 02:54 UTC, ggplay149 commented on order/src/main/java/domain/Cart.java
> +@Table(name = "cart")
복수형으로 수정했습니다!

2024-09-27 02:56 UTC, ggplay149 commented on order/src/main/java/domain/CartItem.java
> +@Table(name = "cartItem")
snake_case 로 수정했습니다!

2024-09-27 03:09 UTC, ggplay149 commented on order/src/main/java/domain/Cart.java
> +    @Column(name = "id", columnDefinition = "varbinary(16)")
원래 @id 만들때  long 사용하다가 
멘토님 프로젝트보고 UUID 따라해봤습니다. 

근데 멘토님 프로젝트에서는 UUID 타입으로 만드셨는데 
코멘트에서는 UUID로 id를 만들더라도 String으로 두는것이 좋다고하셔서

어떤게 맞는건가요?

2024-09-27 03:10 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    @Column(name="status", nullable = false)
UUID 말씀하시는건가요?

확인해보겠습니다!

2024-09-27 03:11 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    private LocalDateTime createdAt;
안그래도 이것때문에 여쭤볼라했는데 

멀티모듈인 상황에서는 BaseEntity를 모듈별로 다 둬야하는건가요?

2024-09-27 03:14 UTC, ggplay149 commented on product/src/main/java/domain/Inventory.java
> +    private BigDecimal stock;
헉 이건 실수입니다. int로 수정하겠습니다

2024-09-27 05:05 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    @ManyToOne(optional = false)
딱히 기준은 없었고 양방향, 단방향 개념이 잘 없었어서
공부해보고 다음처럼 수정했습니다.

cartItem(N) : cart(1) >
cart쪽에 cartItem 리스트를 받기위해 양방향으로 수정

order(N) : cart(1) > 
cart쪽에서 생성되는 여러 order 정보를 참조할 일이 없을것 같아서 단방향 유지

orderItem(N) : order(1) > 
order쪽에서 orderItem 리스트를 받기위해 양방향으로 수정

refund(1) : payment(1) > 
payment에서 refund정보를 참조할 일이 없을것 같아서 단방향 유지

inventory(1) : product(1) >
product 에서 재고량을 참조 할 수 있을것 같아서 양방향으로 수정


이렇게 했습니다.

다른 문제점있으면 말씀부탁드리겠습니다!

2024-09-27 05:08 UTC, ggplay149 commented on order/src/main/java/domain/OrderItem.java
> +    @Column(name = "orderName", nullable = false) //주문당시 상품명
주문당시의 상품명을 기재하고싶어서 그랬는데 생각해보니까 이상한것 같아서

productNameAtOrder 으로 수정했습니다.

2024-09-27 05:08 UTC, ggplay149 commented on order/src/main/java/domain/OrderItem.java
> +    @Column(name = "orderPrice", nullable = false) //주문당시 상품가격
주문당시의 가격을 기재하고싶어서 그랬는데 생각해보니까 이상한것 같아서

productPriceAtOrder 으로 수정했습니다.

좀 이상할까요?

2024-09-27 05:39 UTC, ggplay149 commented on payment/src/main/java/domain/Payment.java
> +    private BigDecimal amount;
1급객체 개념이 없어서 공부했습니다.

1급객체는 
변수에 넣을수 있고, 
함수에 인자값으로 넣을수도 있고,
함수의 결과값으로도 받을수있는 객체라고 이해했습니다.

Payment의 amount
Product의 price 

두개 클래스 따로 빼서 1급객체로 만들었습니다.

금액이나 가격을 1급객체로 따로두라고 하신이유는 
여러가지 계산로직의 관리하기 편해서 인건가요?

2024-09-28 01:42 UTC, DongHyukki commented on order/src/main/java/domain/Cart.java
> +    @Column(name = "id", columnDefinition = "varbinary(16)")
아하 제가 그렇게 해놓은게 있나요??
String 으로 두는게 더 맞다는 생각이 듭니다.
UUID 타입 => 특정 로직을 통해 파생된 String
String 타입 => identify 를 위한 필드 타

굳이 ID 의 타입이 특정 타입으로서 지정될 필요는 없을 것 같습니다.

2024-09-28 01:42 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    @Column(name="status", nullable = false)
UUID 는 아니고 Enum 입니다~!

2024-09-28 01:45 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    private LocalDateTime createdAt;
두가지 방법이 있는데요.

1. 각 모듈별로 둔다.
2. support 모듈을 두고 필요로 하는 것들을 넣어서 관리한다.
3. db 모듈을 두고 거기서 도메인의 entity 들을 관리한다. 

중에 선택하시면 좋을거 같습니다.

정답은 없고 각각 트레이드 오프가 있다보니, 고민해보시고 왜 이방법을 선택했는지만 남겨주시면 좋을거 같습니다.

2024-09-28 01:45 UTC, DongHyukki commented on order/src/main/java/domain/OrderItem.java
> +    @Column(name = "orderPrice", nullable = false) //주문당시 상품가격
괜찮을거 같습니다.

2024-09-28 01:48 UTC, DongHyukki commented on payment/src/main/java/domain/Payment.java
> +    private BigDecimal amount;
넵 말씀하신대로. 별도의 validation 이나 계산 로직들을 1급객체에서 관리할수 있다는 장점이 있고,
primitive 타입 보다 전달하고자 하는 의미가 정확해집니다.

2024-09-28 02:03 UTC, mark-bucketplace requested changes
수고하셨어요. 전체적으로 db 관련해서 snake_case 로 변경 부탁드려요

2024-09-28 02:03 UTC, mark-bucketplace commented on order/src/main/java/domain/Order.java
> +            foreignKey = @ForeignKey(name = "fk_cartItem_to_cart")
보통 DB에 fk 를 물리적으로 걸지 않아요. 엔티티들의 라이프사이클을 관리하기가 어려워집니다.

2024-09-28 02:03 UTC, mark-bucketplace commented on order/src/main/java/domain/Order.java
> +    @Column(name="userId", nullable = false)
user_id

2024-09-30 00:32 UTC, ggplay149 commented on order/src/main/java/domain/Cart.java
> +    @Column(name = "id", columnDefinition = "varbinary(16)")
아넵 String으로 수정하겠습니다!

근데 보통 프로젝트 예제들보면 식별자 id 타입은 long으로 해놓고
1,2,3,4,5,6 이렇게 쭉 시퀀싱 하게 가던데
long을 사용하는 이유는 보통 편의성을 위해서 인가요?

실제 실무에도는 UUID 받고 String으로 저장하는지 궁금합니다

2024-09-30 00:33 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    @Column(name="status", nullable = false)
넵

2024-09-30 00:58 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    private LocalDateTime createdAt;
2번으로 하고 support 모듈 따로 두겠습니다

support모듈을 일종의 공통코드 도메인으로 두고 

BaseEntity말고도 여러가지 공통코드들 관리하는 모듈로

사용하려고합니다 괜찮을까요?

2024-09-30 01:00 UTC, ggplay149 commented on payment/src/main/java/domain/Payment.java
> +    private BigDecimal amount;
넵!

2024-09-30 01:12 UTC, DongHyukki commented on order/src/main/java/domain/Cart.java
> +    @Column(name = "id", columnDefinition = "varbinary(16)")
auto-incerment 를 사용하기 위함일거 같고, 
별도의 ID 채번 / 체계를 가져간다고 하면 String 으로 넣고 idGenerator 를 통해 값을 받는 방식으로 구현합니다.

2024-09-30 01:12 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +            foreignKey = @ForeignKey(name = "fk_cartItem_to_cart")
사실 이것도 멘토님 프로젝트보고 따라해본 부분인데 그럼 실제 fk는 다 제거할까요?

진짜로 fk 거는게 아니라 명시적으로만 걸으라는 말씀이신거죠?

2024-09-30 01:13 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    private LocalDateTime createdAt;
넵 사용해보시고 어떤점이 좋고, 불편한지 고민해보시면 좋을거 같습니다.

2024-09-30 01:13 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    @Column(name="userId", nullable = false)
전체적으로 db관련 모든 컬럼명은 snake_case 로 변경하면될까요?

2024-09-30 01:29 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +            foreignKey = @ForeignKey(name = "fk_cartItem_to_cart")
아 어떤 프로젝트인지 알겠네요 ㅋㅋㅋ 그건 보지마세요 제가 만든게 아닙니다. 예전에 교육받을때 boiler-plate 기반으로 받은 코드에 작업을 하는거였어요.

2024-09-30 01:30 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +            foreignKey = @ForeignKey(name = "fk_cartItem_to_cart")
fk 를 물리적/논리적 중에 논리적으로만 관리하라는 이야기였습니다.

물리적 -> FK 걸기
논리적 -> FK 가 걸려있진 않지만 연관관계가 있다고 가정

2024-09-30 01:31 UTC, DongHyukki commented on order/src/main/java/domain/Order.java
> +    @Column(name="userId", nullable = false)
넵

2024-09-30 01:34 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +            foreignKey = @ForeignKey(name = "fk_cartItem_to_cart")
키친포스 프로젝트엿나? 그거참고했습니다ㅋㅋ

넵 그럼 실제 FK는 제거하고 논리적으로만 가정하겠습니다!

2024-09-30 01:34 UTC, ggplay149 commented on order/src/main/java/domain/Order.java
> +    @Column(name="userId", nullable = false)
넵!

2024-09-30 01:44 UTC, ggplay149 commented on order/src/main/java/domain/Cart.java
> +    @Column(name = "id", columnDefinition = "varbinary(16)")
넵!

2024-09-30 13:55 UTC, merged